gym/myproject/gym/urls.py
from django.urls import path,include
from .views import *

urlpatterns = [
    path('',MainHome.as_view(),name='home'),
    path('about/',about,name='about'),
    path('schedule/',schedule,name='schedule'),
    path('services/',services,name='services'),
    path('galery/',galery,name='galery'),
    path('contact/',contact,name='contact'),
    path('cards/',Member.as_view(),name='cards'),
    path('card__about/<slug:card__about__slug>',ShowPost.as_view(),name='card__about'),
    path('trainer_card/<slug:trainer__slug>',ShowTrainer.as_view(),name='trainer')
    
    # path('trainer/<slug:trainer_slug>',trainer_slug,name='trainer_slug')
    
    
    
    
    
    
    
    
    
]

gym/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from gym.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gym.urls')),
    path('users/',include('users.urls',namespace='users')),
    path('__debug__/',include('debug_toolbar.urls')),
]
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gym/myproject/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    
]

gym/myproject/gym/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify

def translit_to_eng(s: str) -> str:
    d = {'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd',
         'е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i', 'к': 'k',
         'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r',
         'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'c', 'ч': 'ch',
         'ш': 'sh', 'щ': 'shch', 'ь': '', 'ы': 'y', 'ъ': '', 'э': 'r', 'ю': 'yu', 'я': 'ya'}
 
    return "".join(map(lambda x: d[x] if d.get(x, False) else x, s.lower()))


class ModelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=Trainer.Status.ACTIVATED)





class CardAbout(models.Model):
    
    slug = models.SlugField(unique=True,max_length=255,db_index=True,verbose_name='URL')
    image = models.ImageField(upload_to="images/",verbose_name='Картинка карточки')
    title = models.CharField(max_length=255,verbose_name='Заголовок')
    description = models.TextField(blank=True,verbose_name='Описание')
    start_time = models.TimeField(auto_now_add=True,null=True)
    end_time = models.TimeField(auto_now_add=True,null=True)
    trainer_classes = models.ForeignKey('Trainer',on_delete=models.PROTECT,null=True,verbose_name='Тренер')
    membership_type_allow = models.ForeignKey('Membership',on_delete=models.PROTECT,null=True,verbose_name='Абонемент для занятия')
    area_of_text = models.TextField(blank=True,verbose_name='Описание-на сайте')
    
    
    
    
    
    def get_absolute_url(self):
        return reverse("card__about", kwargs={"card__about__slug": self.slug})
    
    def save(self,*args,**kwargs):
        self.slug = slugify(translit_to_eng(self.title))
        super().save(*args,**kwargs)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['slug']
        
        
        indexes = [
            models.Index(fields=['slug'])
        ]
        
        verbose_name = 'Карточку'
        verbose_name_plural = 'Карточки'
        
        
        
        
        
class Members(models.Model):    
        
    first_name = models.CharField(max_length=255,verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    email = models.EmailField(blank=False,unique=True,verbose_name='Почта')
    phone = models.IntegerField(blank=False,unique=True,verbose_name='Телефон')
    membership_type = models.ForeignKey('Membership',on_delete=models.PROTECT,null=True,verbose_name='Тип абонемента')
    membership_start_date = models.DateTimeField(auto_now_add=True,verbose_name='Присоединился(ась)')
    membership_end_date = models.DateTimeField(auto_now_add=True,verbose_name='Дата окончания')
    profile_photo = models.ImageField(upload_to="images/",verbose_name='Фото-профиля',blank=True)
    is_active = models.BooleanField(default=True,verbose_name='Активно')
    trainer = models.ForeignKey('Trainer',models.PROTECT,null=True,verbose_name='Прикрепленный тренер')
     
    
    def __str__(self):
        return self.last_name
    
    class Meta:
        ordering = ['first_name']
        indexes = [
            models.Index(fields=['first_name'])
        ]
        verbose_name = 'Человекa'
        verbose_name_plural = 'Людей'
        
        
        
        
class Membership(models.Model):
    
    slug = models.SlugField(unique=True,max_length=255,db_index=True,verbose_name='URL-Абонемента')
    name= models.CharField(max_length=100,db_index=True,verbose_name='Название абонемента')
    membership_photo = models.ImageField(upload_to="images/",verbose_name='Фото-абонемента')
    price = models.IntegerField(blank=False,unique=True,verbose_name='Цена')
    desc_membership = models.TextField(max_length=255,unique=True,blank=True,verbose_name='Описание абонемента')
    about_membership = models.TextField(max_length=559,blank=True,verbose_name='О абонементе') 
    
    
    def get_absolute_url(self):
        return reverse('membership', kwargs={'membership__slug': self.slug})



    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Абонемент'
        verbose_name_plural = 'Абонементы'
        ordering = ['id','name']
        
        
        
        
class Trainer(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = 0, 'Не тренерует'
        ACTIVATED = 1, 'Тренерует'
        
        
        
        
        
    
    first_name = models.CharField(max_length=255,verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    email = models.EmailField(blank=False,unique=True,verbose_name='Почта')
    phone = models.IntegerField(blank=False,unique=True,verbose_name='Телефон')
    profile_photo = models.ImageField(upload_to="images/",verbose_name='Фото-профиля')
    slug = models.SlugField(unique=True,max_length=255,db_index=True,verbose_name='URL-trainer')
    classes_type = models.ForeignKey('CardAbout',on_delete=models.DO_NOTHING,null=True,verbose_name='Занятия')
    is_active = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]),x[1]),Status.choices)), default=Status.DRAFT,verbose_name='Тренeрует?')
    
    objects = models.Manager()
    act = ModelManager()
    
    
    
    
    
    
    
    
    
    def get_absolute_url(self):
        return reverse('trainer', kwargs={'trainer__slug': self.slug})
    
    
    def __str__(self):
        return self.last_name
    
    def save(self,*args,**kwargs):
        self.slug = slugify(translit_to_eng(self.last_name))
        super().save(*args,**kwargs)
    
    class Meta:
        verbose_name = 'Тренер'
        verbose_name_plural = 'Тренера'
        ordering = ['id','first_name']
        
        indexes = [
            models.Index(fields=['first_name'])
        ]
        
    
    

        
        
    

gym/myproject/gym/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView,DetailView
from .models import *
cats_db = {}


class MainHome(ListView):
    
    template_name = 'main/main_page.html'
    context_object_name = 'cr'

        
        
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cr'] = CardAbout.objects.all
        context['trainer'] = Trainer.act.all().select_related('classes_type')
        context['title'] = 'Главная страница'
        return context

    def get_queryset(self):
        return CardAbout.objects.all().select_related('trainer_classes')




class ShowPost(DetailView):
    model = CardAbout
    template_name = 'main/cards__about.html'
    slug_url_kwarg = 'card__about__slug'
    context_object_name = 'cr'


class ShowTrainer(DetailView):
    model = Trainer
    template_name = 'main/trainercard.html'
    slug_url_kwarg = 'trainer__slug'
    context_object_name = 'trainer'

class Member(ListView):
    template_name = 'main/card.html'
    context_object_name = 'Member'

        
        
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Member'] = Membership.objects.all
        return context

    def get_queryset(self):
        return Membership.objects.all()
  
    



def about(request):
        return render(request,'main/about.html')

def schedule(request):
        return render(request,'main/schedule.html')

def services(request):
        return HttpResponse('3')

def galery(request):
        return HttpResponse('4')

def contact(request):
        return HttpResponse('5')


def cards(request):
        return render(request,'main/card.html')


# def card__about(request,card__about__slug):
#         card = CardAbout.objects.all().select_related('trainer_classes').filter(slug=card__about__slug)
#         trainer = Trainer.act.all().select_related('classes_type')
#         context={
#                 'cr':card,
#                 'trainer':trainer
#         }
        
        
#         return render(request,'main/cards__about.html',context)

gym/myproject/gym/templates/main/about.html
{%extends 'main/base.html'%}
{%load static%}
 
    
{%block about%}

    <div class="about">
        <div class="img"><img src="{% static 'gym/img/about.jpg'%}" alt="" srcset=""></div>
        <div class="container-description-about">
             <h1>О нас</h1>
            <p>THE IMPERIA – это 3 500 кв. м. тренировочного пространства и максимального комплекса фитнес услуг в одном месте.</p></div>    
    </div>

{%endblock%}
{%block cards%}
<section class="card-section-ab">
    <div class="cards-ab">
        <a href="" class="link-card-about">
            <div class="card-ab">
                <div class="card-image-ab">
                  <img src="{% static 'gym/img/about.jpg'%}" alt="Image">
                  <div class="card-text-ab">
                    <h3>Card Title</h3>
                    <p>Card description goes here.</p>
                  </div>
                </div>
              </div>
        </a>

        <a href="" class="link-card-about">
            <div class="card-ab">
                <div class="card-image-ab">
                  <img src="{% static 'gym/img/about.jpg'%}" alt="Image">
                  <div class="card-text-ab">
                    <h3>Card Title</h3>
                    <p>Card description goes here.</p>
                  </div>
                </div>
              </div>
        </a>

        <a href="" class="link-card-about">
            <div class="card-ab">
                <div class="card-image-ab">
                  <img src="{% static 'gym/img/about.jpg'%}" alt="Image">
                  <div class="card-text-ab">
                    <h3>Card Title</h3>
                    <p>Card description goes here.</p>
                  </div>
                </div>
              </div>
        </a>

        <a href="" class="link-card-about">
            <div class="card-ab">
                <div class="card-image-ab">
                  <img src="{% static 'gym/img/about.jpg'%}" alt="Image">
                  <div class="card-text-ab">
                    <h3>Card Title</h3>
                    <p>Card description goes here.</p>
                  </div>
                </div>
              </div>
        </a>

        <a href="" class="link-card-about">
            <div class="card-ab">
                <div class="card-image-ab">
                  <img src="{% static 'gym/img/about.jpg'%}" alt="Image">
                  <div class="card-text-ab">
                    <h3>Card Title</h3>
                    <p>Card description goes here.</p>
                  </div>
                </div>
              </div>
        </a>

        <a href="" class="link-card-about">
            <div class="card-ab">
                <div class="card-image-ab">
                  <img src="{% static 'gym/img/about.jpg'%}" alt="Image">
                  <div class="card-text-ab">
                    <h3>Card Title</h3>
                    <p>Card description goes here.</p>
                  </div>
                </div>
              </div>
        </a>

        <a href="" class="link-card-about">
            <div class="card-ab">
                <div class="card-image-ab">
                  <img src="{% static 'gym/img/about.jpg'%}" alt="Image">
                  <div class="card-text-ab">
                    <h3>Card Title</h3>
                    <p>Card description goes here.</p>
                  </div>
                </div>
              </div>
        </a>

        <a href="" class="link-card-about">
            <div class="card-ab">
                <div class="card-image-ab">
                  <img src="{% static 'gym/img/about.jpg'%}" alt="Image">
                  <div class="card-text-ab">
                    <h3>Card Title</h3>
                    <p>Card description goes here.</p>
                  </div>
                </div>
              </div>
        </a>

        

        
        
        
    



    </div>
</section>

    

{%endblock cards%}

gym/myproject/gym/templates/main/base.html
{%load static%}
{%load gym_tags%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{%static 'gym/css/style.css'%}">
    <link rel="stylesheet" href="{%static 'gym/css/about.css'%}">
    <link rel="stylesheet" href="{%static 'gym/css/schedule.css'%}">
    <link rel="stylesheet" href="{%static 'gym/css/card.css'%}">
    <link rel="stylesheet" href="{%static 'gym/css/main-card.css'%}">
    <link rel="stylesheet" href="{%static 'gym/css/trainer.css'%}">
    <link rel="icon" type="image/ico" href="{%static 'gym/ico/free-icon-gym-machine-3349382.png'%}">

    <script defer src="{% static 'gym/js/scripts.js'%}"></script>
</head>
<body>

    <section class="navigation">
        <header class="header">
           
                <div class="container-nav">
                    <button class="Header-btn-burger" id="Burger">
                        <span></span><span></span><span></span>
                    </button>
                
                    {%get_menu as menu%}
                    
                    <ul class="nav-list">
                        {%for m in menu%}
                        <li class="navlistitem"><a href="{% url m.url_name %}">{{m.title}}</a></li>
                        {% endfor %}
                        {% if user.is_authenticated %}
                        <li class="navlistitem"> {{user.username}} | <a href="{% url 'users:logout' %}">Выйти</a></li>
                        {% else %}
                        <li class="navlistitem"><a href="{% url 'users:login' %}">Войти</a> | <a href="{% url 'users:register' %}">Регистрация</a></li>
                        {% endif %}
                    </ul>
                    
                </div>
        </header>
    </section>



    {% block headsection %}{% endblock %}
    {%block about%} {%endblock about%}
    {%block content%} {%endblock content%}
    {%block cards%}{%endblock%}
    {% block reception %}{%endblock%}
    {% block trainers %}{%endblock%}





    



            <footer class="footer">

                <div class="container-f">
                    <div class="row">
                      <div class="footer-col">
                       
                          Брянск, ул. Дуки 69 Ост. "Курган Бессмертия"

                          +7 (4832)30-36-07
                          |
                          30-36-30
                          imperia-op@yandex.ru
                          Все права защищены 2013-2024 © Фитнес-клуб «THE IMPERIA»

                          Политика обработки персональных данных
                          Сайт разработан студией RBand
                        </div>
                      </div>
                    </div>
                   </div>
            </footer>
       
       
       
       
        </div>
    </section>
</body>
</html>

gym/myproject/gym/templates/main/card.html
{%extends 'main/base.html'%}
{%load static%}


{%block content%}
    <section class="description-second__section">
        <div class="img-desc-sec"><img src="{%static 'gym/img/kartavip_1920x804.jpg'%}" alt="#"></div>
        <div class="description-second__sec">
            <h1 class="desc-card__title">КАРТЫ «THE IMPERIA»</h1>
            <p>Хотите вступить в клуб активных, позитивных и уверенных в себе людей? Тогда вам сюда! Выберите подходящее для вас членство в фитнес-клубе «THE IMPERIA».</p></div>
    </section>




    <section class="wrapper-ad">
            <h2>КЛУБНАЯ КАРТА THE IMPERIA – ВАША ПРИВИЛЕГИЯ!</h2>
            <p>Подробности уточняйте по телефону: +7 (4832) 30-36-07</p>
    </section>


    {%endblock content%}


    {%block cards%}
    <section class="main-container-card-sec">

    {%for f in Member%}
        <div class="container-card-sec">
            <div class="title-card-sec">{{f.name}}</div>
        {%if f.membership_photo%}
            <div class="img-sec"><img src="{{f.membership_photo.url}}" alt="" srcset=""></div>
        {%endif%}
            <div class="price-list">{{f.price}}</div>
            <div class="description-card-sec">{{f.desc_membership}}</div>
            <div class="link-buy"><a href="#">Заказать карту</a></div>
        </div>
        
    {%endfor%}


    </section>
    {%endblock%}

gym/myproject/gym/templates/main/cards__about.html
{%extends 'main/base.html'%}
{%load static%}
{%block content%}


    <div class="image-wrapper">
        {% if cr.image %}
            <img src="{{cr.image.url}}" alt="" srcset="">
        {% endif %}
    
        <div class="wrap">
            <div class="container-about-classes">
                <div class="classes-title">
                    <h2>{{cr.title}}</h2>
                </div>
                <div class="classes-desc">
                    <p>{{cr.description}}</p></div>
            </div>
            <div class="wrapper-all-about">
                
                <div class="desc-wrapper">{{cr.area_of_text}}</div>
            </div>
        </div>
    </div>

{%endblock%}

gym/myproject/gym/templates/main/main_page.html
{% extends "main/base.html" %}


{%load static%}

{% block headsection %}
<section class="head-section">
    <div class="intro">
        <div class="videos">
            <div class="video__media">
               <video src="{% static 'gym/img/diplom-video-gym.mp4' %}" autoplay muted loop></video>
           </div>
       </div>
          
    </div>
    
    
    
    
    
    <div class="head-content">
        <h1>ПУТЬ К СОВЕРШЕНСТВУ НАЧИНАЕТСЯ ЗДЕСЬ</h1>
        <p>«THE IMPERIA» – это содружество активных, позитивных и 
            уверенных в себе людей. Разнообразие тренировок и 
            спортивных активностей впечатлит даже самого
             искушенного поклонника фитнеса.
        </p>
        <div class="btns">
            <a href="" class="btn">Запись к тренеру</a>
            <a href="{% url 'cards' %}" class="btn">Выбрать карту</a>
        </div>
    </div>
</section>

<section class="section-public">
    <div class="container-public">
        <div class="public"><p class="title-public">
            <strong>КОМАНДА ПРОФЕССИОНАЛОВ</strong></p>
            <p class="desc-public">Наши тренеры – профессионалы своего дела. Они индивидуально подходят к работе с клиентом, что позволяет достичь целей в оптимальные сроки.</p>
        </div>
        <div class="public"><p class="title-public">
            <strong>НОВЕЙШЕЕ ОБОРУДОВАНИЕ</strong></p>
            <p class="desc-public">Залы оснащены новейшим оборудованием. Более 80 тренажеров дают возможность даже при полной загрузке зала заниматься с минимальным ожиданием.</p>
        </div>
        <div class="public">
            <p class="title-public"><strong>ЦЕНТР ПРИТЯЖЕНИЯ</strong></p>
            <p class="desc-public">Клуб расположен в центре города на 3-х этажах площадью более 3 500 м2. Здесь есть всё для совершенствования себя, подготовки к новым победам и релакса.                </p>
        </div>
    </div>
</section>
{% endblock  %}
{%block cards%}

<section class="card-section-ab">

  <div class="cards-ab">
    {%for p in cr%}
      <a href="{{p.get_absolute_url}}" class="link-card-about">
          <div class="card-ab">
              <div class="card-image-ab">
                {%if p.image%}
                <img src="{{p.image.url}}" alt="Image">
                {%endif%}
                <div class="card-text-ab">
                  <h3>{{p.title}}</h3>
                  <p>{{p.description}}</p>
                </div>
              </div>
            </div>
      </a>
      {%endfor%}
    </div>



</section>

  
 



</section>
{%endblock%}

{% block reception %}
<section class="reception">
    
  <div class="reception-block">
      

      <div class="reception-subscribe">
          <div class="reception-title">РЕСЕПШН</div>
          <div class="reception-desc">«THE IMPERIA» – это место, которое лучше один раз увидеть. Клуб расположен в центре города на трех этажах площадью более 3 500 м3. Здесь каждый найдет себе занятие по душе!</div>
      </div>
          


  </div>
</section>
{% endblock reception %}

{% block trainers %}
<section class="trainers-sec"><h2>Наш тренерский состав</h2>
  <div class="trainers">

      
    <div class="cards-ab">
        {%for tr in trainer%}
          <a href="{{tr.get_absolute_url}}" class="link-card-about">
              <div class="card-ab">
                  <div class="card-image-ab">
                    {%if tr.profile_photo%}
                    <img src="{{tr.profile_photo.url}}" alt="Image">
                    {%endif%}
                    <div class="card-text-ab">
                      <h3>{{tr.first_name}} {{tr.last_name}}</h3>
                      <p>{{tr.classes_type}}</p>
                    </div>
                  </div>
                </div>
          </a>
          {%endfor%}
        </div>
      
  </div>
</section>
{% endblock trainers %}


    


            
            
   
</body>
</html>

gym/myproject/gym/templates/main/schedule.html
{%extends 'main/base.html'%}
{%load static%}

{%block cards%}
    <div class="back-img"><img src="{%static 'gym/img/bacground-schedule.jpg'%}"></div>
    <div class="container_schedule">
        <div class="schedule_title">Расписание занятий</div>
        
        
        <div class="schedule_blocks">

            <div class="schedule_block">
                <div class="schedule_img"><img src="{%static 'gym/img/card-training-shed.jpg'%}"></div>
                <div class="schedule_title-card">
                    <div class="trainers-name">Dmitry Makarov</div>
                    <div class="trainer-desc">training foream,chest, and</div>
                </div>
                <div class="schedule_desc">13:40 - monday 13:40 - monday 13:40 - monday 13:40 - monday 13:40 - monday <a href="#">Записаться</a> </div>
            </div>
            <div class="schedule_block">
                <div class="schedule_img"><img src="{%static 'gym/img/card-training-shed.jpg'%}"></div>
                <div class="schedule_title-card">
                    <div class="trainers-name">Dmitry Makarov</div>
                    <div class="trainer-desc">training foream,chest, and</div>
                </div>
                <div class="schedule_desc">13:40 - monday 13:40 - monday 13:40 - monday 13:40 - monday 13:40 - monday <a href="#">Записаться</a> </div>
            </div>
            <div class="schedule_block">
                <div class="schedule_img"><img src="{%static 'gym/img/card-training-shed.jpg'%}"></div>
                <div class="schedule_title-card">
                    <div class="trainers-name">Dmitry Makarov</div>
                    <div class="trainer-desc">training foream,chest, and</div>
                </div>
                <div class="schedule_desc">13:40 - monday 13:40 - monday 13:40 - monday 13:40 - monday 13:40 - monday <a href="#">Записаться</a> </div>
            </div>
            <div class="schedule_block">
                <div class="schedule_img"><img src="{%static 'gym/img/card-training-shed.jpg'%}"></div>
                <div class="schedule_title-card">
                    <div class="trainers-name">Dmitry Makarov</div>
                    <div class="trainer-desc">training foream,chest, and</div>
                </div>
                <div class="schedule_desc">13:40 - monday 13:40 - monday 13:40 - monday 13:40 - monday 13:40 - monday <a href="#">Записаться</a> </div>
            </div>
            
           

            
                       

        </div>
    </div>

{%endblock%}

gym/myproject/gym/templates/main/trainercard.html
{% extends "main/base.html" %}
{%load static%}

{%block content%}
    
        <section class="head-title-trainer">
            <div class="trainer-cont">
                <div class="trainer-cont-wrapper">
                    {%if trainer.profile_photo%}
                    <div class="img-trainer">
                        <img src="{{trainer.profile_photo.url}}" alt="" srcset=""></div>
                    <div class="c-trainer">
                        {%endif%}
                        <div class="title-trainer">Привет меня зовут {{trainer.first_name}} , и я тренер  {{trainer.classes_type}}</div>
                        <div class="description-trainer">
                            <a href="{% url 'home' %}">На главную</a>
                            <a href="#">Записаться</a>
                            <div class="email">{{trainer.email}}</div>
                        </div>



                </div>
            
            </div>
                
            </div>
        </section>


   

{%endblock%}